### ISSUE TITLE
Add custom text transformations

### ISSUE THREAD

**Issue by bmarty** [NijiDigital/poesie#1]
As a user of poeditor script, I want to pass a list of {string + replacement string} as parameter of the script to apply custom changes on the strings extracted from POEditor.

Example: Add unbreakable space between two words
"The Times" => "The\u00A0Times"

Acceptance criteria:
- All strings (including plurals and CDATA strings) matching any term of the list are replaced by the corresponding terms

**Comment by AliSoftware** [comment]
Good idea. Would it be ok to pass those in the command line parameters with something like `--replace "The Times" "The\u00A0Times"`?

**Comment by bmarty** [comment]
Yes, if we can pass several --replace options
