### ISSUE TITLE
SSLv3 Certificate verify failed

### ISSUE THREAD

**Issue by ClementHard** [NijiDigital/poesie#14]
When using **poesie** on windows, i get the following exception:

```
C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:852:in `start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:584:in `start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:508:in `post_form'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/poesie-1.5.0/lib/exporter.rb:45:in `generate_export_uri'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/poesie-1.5.0/lib/exporter.rb:26:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/poesie-1.5.0/bin/poesie:84:in `<top (required)>'
        from C:/Ruby23-x64/bin/poesie:22:in `load'
        from C:/Ruby23-x64/bin/poesie:22:in `<main>'
```

Is there any workaround available ?

**Comment by ClementHard** [comment]
I fixed the issue using this workaround : http://railsapps.github.io/openssl-certificate-verify-failed.html

**Comment by AlainMuller** [comment]
@Twibit This worked like a charm, thank you! 😄
Based on your link, [here ](https://gist.github.com/fnichol/867550#the-manual-way-boring) are the instructions for my Windows laptop :

1. Download the missing SSL certificate _cacert.pem_ [here](http://curl.haxx.se/ca/cacert.pem) and place it somewhere safe,

2. Add its path to the specific environment variable : 
`set SSL_CERT_FILE=C:\MyCustomFolder\cacert.pem`

**Comment by AliSoftware** [comment]
Maybe we should add this in the documentation somewhere so that other people using Windows will have instructions about how to solve this problem?

**Comment by afaucogney** [comment]
Issue can be found to find the workaround. I can close the issue.
