### ISSUE TITLE
Error when processing Asian strings for iOS

### ISSUE THREAD

**Issue by a-bass** [NijiDigital/poesie#18]
I have issues with Asian translations for iOS, like "ko" and "zh-Hans". For example, when downloading Korean translations, it stops at "- Processing generated strings..." with the following as the most recent call in the traceback:

…/.rvm/gems/ruby-2.5.0/gems/poesie-1.5.0/lib/apple_formatter.rb:49:in \`block in write_strings_file\': **undefined method \`gsub\' for nil:NilClass (NoMethodError)**

I've managed to solve it just by changing `.gsub` to `context.gsub` at the lines 49 to 52 in the file "apple_formatter.rb". Not sure what causing it but it seems related to placeholders without trailing spaces.

**Comment by afaucogney** [comment]
this issue can be closed as the mr has been merge. Please reopen if required
