### ISSUE TITLE
Version `1.5.2` is not reachable via `https://rubygems.org/`

### ISSUE THREAD

**Issue by laxmorek** [NijiDigital/poesie#24]
**Problem**
The newest available version on https://rubygems.org/ is `1.5.1`. List of available versions: https://rubygems.org/gems/poesie

**Expected behavior**
I should be able to fetch version `1.5.2` using `source 'https://rubygems.org'` in my `Gemfile`.

**Temporary workaround**
I have added `gem 'poesie', git: 'https://github.com/NijiDigital/poesie'` to my `Gemfile`.

**Comment by afaucogney** [comment]
Hi @laxmorek, thanks for your issue, and thank for speeding up me ! 
This is under progress, I had some issue by getting access right with ruby gems. This will be solved soon. I ll keep you updated.

**Comment by afaucogney** [comment]
@laxmorek this is done since a couple day. Re open it if you are going into issue.
