### ISSUE TITLE
Failed to resolve dependencies with cocoapods 1.10

### ISSUE THREAD

**Issue by StevenWatremez** [NijiDigital/poesie#25]
Hi, I tried to update my cocoapods to 1.10 and I had a problem with poesie I guess. Gem install fail to resolve `activesupport`.

```ruby
Bundler could not find compatible versions for gem "activesupport":
   In Gemfile:
    cocoapods (= 1.10.0) was resolved to 1.10.0, which depends on
    cocoapods-core (= 1.10.0) was resolved to 1.10.0, which depends on
    activesupport (< 6, > 5.0)
  
    poesie was resolved to 1.5.1, which depends on
    activesupport (~> 4.2)
  
    slather was resolved to 2.5.0, which depends on
    activesupport
```

It's ok if I downgrade to cocoapods to 1.9 but I have a pod (Stripe in 20.1.1) that requires 1.10 because they break the compat. 

I analyse poesie and for me the problem may be comes from `net` gem that has not been updated since 2013. Maybe this gem could be replaced by a most used/popular gem.

What do you think about this ?

**Comment by StevenWatremez** [comment]
For people who encountered this problem you can find the patch in the version `1.5.2` of poesie. But for now this version is not released in rubygems. So you can download the binary or if you use a gemfile refer the master branch like this :
```ruby
gem 'poesie', :git => "git://github.com/NijiDigital/poesie", :branch => "master"
```

**Comment by afaucogney** [comment]
This has been solve with the latest release
