### ISSUE TITLE
Missing ruby dependencies are not managed

### ISSUE THREAD

**Issue by bmarty** [NijiDigital/poesie#3]
As a user of poeditor, I do not want to be stuck with a awefull stacktrace when a ruby dependencie is missing

The script should check that dependencies are available and should fail with an explicite message when a dependencie is missing

Example:
“'builder' modul not found, please run ‘gem install builder’”

**Comment by AliSoftware** [comment]
The installation instructions have been updated accordingly, with all steps explained in details, so this should not happen anymore.
