### ISSUE TITLE
Add option to trim values

### ISSUE THREAD

**Issue by bmarty** [NijiDigital/poesie#5]
--trim

**Comment by AliSoftware** [comment]
If we decide to make `--replacements` support regular expressions (in addition to plain text) this would cover that case… and much more (using regexp like `/^\s*/` and `/\s*$/` and replacing each with the empty string)

**Comment by AliSoftware** [comment]
Support for RegExps has been added so you can now do it with `/^\s+/` and `/\s+$/` :wink:
