### ISSUE TITLE
Not specifying --lang should export all the available languages

### ISSUE THREAD

**Issue by bmarty** [NijiDigital/poesie#8]
Is it possible to export all translations in all languages if --lang is not specified?

**Comment by AliSoftware** [comment]
I'm not sure that's entirely suitable. For example, on iOS you need to specify a different output folder for each language you export, so I'm not sure how the command line arguments specifying the output file would look in this case? As you'd have to specify multiple output files, one for each language

(I don't even know how that works for Android, but I'm guessing it's the same, you have to store the `strings.xml` files for each language in a different folder?)

**Comment by AliSoftware** [comment]
Also note that you can simply do a simple loop in shell in the meantime:
```sh
for lang in fr en es jp pt de
do
  poesie -t … -p … -l $lang -a …
done
```

Or as one-liner:
```sh
for lang in fr en es jp pt de; do poesie -t … -p … -l $lang -a …; done
```

**Comment by bmarty** [comment]
Thanks for the suggestion
