### ISSUE TITLE
Substitution with key containing space does not work

### ISSUE THREAD

**Issue by bmarty** [NijiDigital/poesie#9]
if substitution file contains key with space, substitution will not be done.

Example:
"The test": "The good test"

"The test" will not be replaced by "The good test"

**Comment by AliSoftware** [comment]
Errr could you give more details? When I test it myself it works.

```
- " :": "\u00A0:"
  " ;": "\u00A0;"
  " !": "\u00A0!"
  " ?": "\u00A0?"
- "...": "…"
- "un seul": "seulement un"
- /^\s+/: ""
  /\s+$/: ""
```

And "un seul" is properly replaced in my tests with "seulement un".

Are you sure that e.g. the text in your translations doesn't contain a non-breaking space or invisible character or something (worth checking with an hex editor for example)

**Comment by bmarty** [comment]
Ok my mistake, an unbreakable space was hidden in my code.
